### ISSUE TITLE
'super' object has no attribute 'generate'... Issues following example...

### ISSUE THREAD

**Issue by epb378** [facebookresearch/GENRE#25]
Hey, I have been having a few issues with getting the basic example to work on colab (python version = 3.7.10)

If I install GENRE from the cloned repo and install fairseq from the branch you suggest I can't import GENRE from genre.fairseq_model.py:

```import pickle
from genre.fairseq_model import GENRE
```

gives

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-8d627c96b455> in <module>()
      1 import pickle
----> 2 from genre.fairseq_model import GENRE
      3 from genre.entity_linking import get_end_to_end_prefix_allowed_tokens_fn_fairseq as get_prefix_allowed_tokens_fn
      4 from genre.utils import get_entity_spans_fairseq as get_entity_spans
      5 model = GENRE.from_pretrained("../models/fairseq_e2e_entity_linking_aidayago").eval()

2 frames
/content/gdrive/MyDrive/entity_linking_demo/fairseq/fairseq/criterions/__init__.py in <module>()
     22     CRITERION_DATACLASS_REGISTRY,
     23 ) = registry.setup_registry(
---> 24     "--criterion", base_class=FairseqCriterion, default="cross_entropy"
     25 )
     26 

TypeError: cannot unpack non-iterable NoneType object
```

So then I tried installing GENRE from the cloned repo and !pip install fairseq and I got further

```
import pickle
import genre
from genre.trie import Trie
from genre.fairseq_model import GENRE
with open("kilt_titles_trie_dict.pkl", "rb") as f:
    trie = Trie.load_from_dict(pickle.load(f))
model = GENRE.from_pretrained("fairseq_entity_disambiguation_aidayago").eval()
model.sample(sentences=["Einstein was a [START_ENT] German [END_ENT] physicist."])
```

Which gives...

```
1042301B [00:00, 1105195.62B/s]
456318B [00:00, 601446.35B/s]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-f9cae36978b8> in <module>()
      6     trie = Trie.load_from_dict(pickle.load(f))
      7 model = GENRE.from_pretrained("fairseq_entity_disambiguation_aidayago").eval()
----> 8 model.sample(sentences=["Einstein was a [START_ENT] German [END_ENT] physicist."])

1 frames
/content/drive/MyDrive/entity_linking_demo/GENRE/genre/fairseq_model.py in sample(self, sentences, beam, verbose, text_to_id, marginalize, marginalize_lenpen, max_len_a, max_len_b, **kwargs)
     41             max_len_a=max_len_a,
     42             max_len_b=max_len_b,
---> 43             **kwargs,
     44         )
     45         outputs = [

/content/drive/MyDrive/entity_linking_demo/GENRE/genre/fairseq_model.py in generate(self, *args, **kwargs)
     90 
     91     def generate(self, *args, **kwargs) -> List[List[Dict[str, torch.Tensor]]]:
---> 92         return super(BARTHubInterface, self).generate(*args, **kwargs)
     93 
     94 

AttributeError: 'super' object has no attribute 'generate'
```

I'm probably doing something pretty stupid, but just trying to follow the examples as I read them. I got the same `TypeError: super()... ` when I tried a couple of different models. Any advice?

**Comment by nicola-decao** [comment]
The first error is very strange, I have no idea where it comes from.

The second is due to `!pip install fairseq` that probably installs a different version than the one required. You should install my fork as in the official fariseq they didn't fix the bug yet.

**Comment by epb378** [comment]
Thanks for the reply! As I said, when i cloned the branch and installed it as suggested I got the first error. There were also a whole host of other weird dependency issues like omegaconf and hydra, but reinstalling them seemed to fix it. I'll keep trying:)

**Comment by nicola-decao** [comment]
Any news on this?

**Comment by epb378** [comment]
I gave up! project moved on and I couldn't get it to work, sorry!

**Comment by HuiBinR** [comment]
Prepare the working environment follow the below link is useful.
https://github.com/jingjunlu2001/image_retrieval/blob/60b10d2539c22f35ae80299b7b4339997b30cdea/genre.ipynb

My solution to solve the error: AttributeError: 'super' object has no attribute 'generate'  is to uninstall the fairseq. And use command 'pip install -e ./fairseq'  after clone the fairseq branch.

**Comment by nicola-decao** [comment]
@HuiBinR yes this is how my instructions are (see https://github.com/facebookresearch/GENRE/tree/main/examples_genre)
